# Project information
site_name: Plants&Python
site_url: https://danchitwood.github.io/plants_and_python/
site_author: Dan Chitwood
site_description: Learn to code in Python / aprender a programar en python


# Repository
repo_name: DanChitwood/plants_and_python
repo_url: https://github.com/DanChitwood/plants_and_python

# Copyright
copyright: Copyright &copy; 2025 Dan Chitwood, Alejandra Rougon-Cardoso, Robert VanBuren


# Configuration
theme:
  name: material
  features:
    - announce.dismiss
    #- content.action.edit
    #- content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  font: 
    text: Roboto
    code: Red Hat Mono
  logo: assets/icon.png
  favicon: assets/icon.png
  icon:
    repo: fontawesome/brands/git-alt

# Page tree
nav:
  - Home | Inicio: index.md
  - Getting started | Empezando:
    - Installation | Instalación: 00_Installing_Anaconda.md
    - Coding cells | celdas de código: 02_Coding_cells.md
    - Markdown cells | celdas de markdown: 04_Markdown_cells.md
  - Quick start: OAXACA_workshop.md


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@DanChitwood
    - icon: simple/python
      link: https://plantsandpython.github.io/PlantsAndPython/00_Opening_page.html


